@startuml userManagementUseCase

left to right direction
rectangle "Usermanagement" {
    
actor "Project owner" as po

rectangle "Phlowr Application" as app #SkyBlue{
    usecase "add user" as addUser
    usecase "manage users" as manageUsers
    usecase "change permissions" as changePermissions
    usecase "manage users" as manageUsers
    usecase "manage users" as manageUsers

}

po -d-> addUser
po -d-> manageUsers
manageUsers ..> changePermissions:<<include>>

}




@enduml